/*
  Copyright (C) U2HTS Developers. All rights reserved.
  U2HTS stands for "USB to HID TouchScreen".
  mxt1188s1.c: touch driver for Atmel maxTouch mxt1188s1 touch controllers.
  This file is licensed under GPL V3.
*/

#include "u2hts_core.h"
#include <string.h>

static bool mxt1188s1_setup(U2HTS_BUS_TYPES bus_type);
static bool mxt1188s1_service(void);
static void mxt1188s1_get_config(u2hts_touch_controller_config* cfg);

static u2hts_touch_controller_operations mxt1188s1_ops = {
    .setup = &mxt1188s1_setup,
    .fetch = &mxt1188s1_service,
    .get_config = &mxt1188s1_get_config
};

static u2hts_touch_controller mxt1188s1 = {
    .name = "mxt1188s1",
    .irq_type = IRQ_TYPE_LEVEL_LOW,
    .report_mode = UTC_REPORT_MODE_EVENT,
    .i2c_config =
        {
            .primary_addr = 0x4a,
            .alt_addrs = (uint8_t[]){0x4b, 0},
            .speed_hz = 400 * 1000,
        },
    .operations = &mxt1188s1_ops
};

U2HTS_TOUCH_CONTROLLER(mxt1188s1);

#define MXT1188S1_I2C_ADDR mxt1188s1.i2c_config.primary_addr
#define MXT1188S1_FAMILY_ID 0xA2
#define MXT1188S1_VARIANT_ID 0x01

#define MXT1188S1_T9_STATUS_DETECT   (1 << 7)
#define MXT1188S1_T9_STATUS_PRESS    (1 << 6)
#define MXT1188S1_T9_STATUS_RELEASE  (1 << 5)
#define MXT1188S1_T9_STATUS_MOVE     (1 << 4)
#define MXT1188S1_T9_STATUS_VECTOR   (1 << 3)
#define MXT1188S1_T9_STATUS_AMP      (1 << 2)
#define MXT1188S1_T9_STATUS_SUPPRESS (1 << 1)
#define MXT1188S1_T9_STATUS_UNGRIP   (1 << 0)

#define MXT1188S1_T6_STATUS_COMSERR  (1 << 2)
#define MXT1188S1_T6_STATUS_CFGERR   (1 << 3)
#define MXT1188S1_T6_STATUS_CAL      (1 << 4)
#define MXT1188S1_T6_STATUS_SIGERR   (1 << 5)
#define MXT1188S1_T6_STATUS_OFL      (1 << 6)
#define MXT1188S1_T6_STATUS_RESET    (1 << 7)

inline static bool mxt1188s1_read(uint16_t addr, void* buf, size_t len) {
  uint8_t addr_buf[2] = { (uint8_t)(addr & 0xFF), (uint8_t)((addr >> 8) & 0xFF) };

  if (!buf || len == 0) {
    U2HTS_LOG_ERROR("%s invalid parameters, buf = %p, len = %zu", __func__, buf, len);
    return false;
  }

  // Send 16-bit address with re-start (stop = false)
  if (!u2hts_i2c_write(MXT1188S1_I2C_ADDR, addr_buf, sizeof(addr_buf), false)) {
    U2HTS_LOG_ERROR("%s write address error, addr = 0x%04x", __func__, addr);
    return false;
  }

  // Read data following restart
  if (!u2hts_i2c_read(MXT1188S1_I2C_ADDR, buf, len)) {
    U2HTS_LOG_ERROR("%s read error, addr = 0x%04x", __func__, addr);
    return false;
  }

  return true;
}

inline static bool mxt1188s1_write(uint16_t addr, const void* buf, size_t len) {
  uint8_t tx_buf[2 + len];
  tx_buf[0] = (uint8_t)(addr & 0xFF);
  tx_buf[1] = (uint8_t)((addr >> 8) & 0xFF);

  if (!buf || len == 0) {
    U2HTS_LOG_ERROR("%s invalid parameters, buf = %p, len = %zu", __func__, buf, len);
    return false;
  }

  memcpy(tx_buf + 2, buf, len);

  if (!u2hts_i2c_write(MXT1188S1_I2C_ADDR, tx_buf, 2 + len, true)) {
    U2HTS_LOG_ERROR("%s write error, addr = 0x%04x", __func__, addr);
    return false;
  }

  return true;
}


// Controller object table element (6 bytes)
typedef struct __packed {
  uint8_t  type;
  uint16_t start_address; // 16-bit little-endian
  uint8_t  size;          // size - 1
  uint8_t  instances;     // instances - 1
  uint8_t  num_report_ids;
} mxt1188s1_object_table_element_t;

// Controller Information Block header (7 bytes + object table)
typedef struct __packed {
  uint8_t family_id;
  uint8_t variant_id;
  uint8_t version;
  uint8_t build;
  uint8_t matrix_x_size;
  uint8_t matrix_y_size;
  uint8_t num_objects;
  mxt1188s1_object_table_element_t object_table[];
} mxt1188s1_information_block_t;

// TOUCH_MULTITOUCHSCREEN_T9 message data (7 bytes payload following report_id)
typedef struct __packed {
  uint8_t status;       // Byte 1: Status bitmask
  uint8_t xposmsb;      // Byte 2: X position MSB
  uint8_t yposmsb;      // Byte 3: Y position MSB
  uint8_t xyposlsb;     // Byte 4: X LSB (bits 7:4), Y LSB (bits 3:0)
  uint8_t tcharea;      // Byte 5: Size of touch
  uint8_t tchamplitude; // Byte 6: Touch amplitude / pressure
  uint8_t tchvector;    // Byte 7: Touch vector
} mxt1188s1_report_t9_t;

// Report generated by T6: Configuration Status
typedef struct __packed {
  uint8_t status;       // Byte 1: Status bitmask
  uint8_t checksum[3];  // Bytes 2-4: Configuration checksum
} mxt1188s1_report_t6_t;

// T7: Power Configuration structure (4 bytes)
typedef struct __packed {
  uint8_t idleacqint;   // Byte 0: Idle acquisition interval (ms)
  uint8_t actvacqint;   // Byte 1: Active acquisition interval (ms) -> 10 = 100Hz
  uint8_t actv2idleto;  // Byte 2: Active to Idle timeout (x 200ms)
  uint8_t cfg;          // Byte 3: Config flags (bits 0: IDLEPIPEEN, 1: ACTVPIPEEN)
} mxt1188s1_t7_power_config_t;

// T9: Configuration structure for TOUCH_MULTITOUCHSCREEN_T9 (47 bytes)
typedef struct __packed {
    uint8_t ctrl;             /* 0: Control register (Bitfield: SCANEN, DISPRSS, DISREL, DISMOVE, DISVECT, DISAMP, RPTEN, ENABLE) */
    uint8_t xorigin;          /* 1: X line start position of object */
    uint8_t yorigin;          /* 2: Y line start position of object */
    uint8_t xsize;            /* 3: Number of X lines the object occupies */
    uint8_t ysize;            /* 4: Number of Y lines the object occupies */
    uint8_t akscfg;           /* 5: Adjacent Key Suppression config (Groups 1-8) */
    uint8_t blen;             /* 6: Gain (Burst Length) */
    uint8_t tchthr;           /* 7: Touch threshold */
    uint8_t tchdi;            /* 8: Touch detect integration for first touch */
    uint8_t orient;           /* 9: Orientation (Bitfield: INVERTY, INVERTX, SWITCH) */
    uint8_t mrgtimeout;       /* 10: Merge timeout */
    uint8_t movhysti;         /* 11: Movement hysteresis, initial */
    uint8_t movhystn;         /* 12: Movement hysteresis, next */
    uint8_t reserved_13;      /* 13: Reserved */
    uint8_t numtouch;         /* 14: Number of reported touches */
    uint8_t mrghyst;          /* 15: Merge hysteresis */
    uint8_t mrgthr;           /* 16: Merge threshold */
    uint8_t amphyst;          /* 17: Amplitude hysteresis */
    uint8_t xrangelsb;        /* 18: X resolution (low byte) */
    uint8_t xrangemsb;        /* 19: X resolution (high byte) */
    uint8_t yrangelsb;        /* 20: Y resolution (low byte) */
    uint8_t yrangemsb;        /* 21: Y resolution (high byte) */
    uint8_t xloclip;          /* 22: X low clipping boundary width */
    uint8_t xhiclip;          /* 23: X high clipping boundary width */
    uint8_t yloclip;          /* 24: Y low clipping boundary width */
    uint8_t yhiclip;          /* 25: Y high clipping boundary width */
    uint8_t xedgectrl;        /* 26: X edge control (Bitfield: SPAN, DISLOCK, CORRECTIONGRADIENT) */
    uint8_t xedgedist;        /* 27: X edge correction distance */
    uint8_t yedgectrl;        /* 28: Y edge control (Bitfield: SPAN, RELUPDATE, CORRECTIONGRADIENT) */
    uint8_t yedgedist;        /* 29: Y edge correction distance */
    uint8_t jumplimit;        /* 30: Maximum position jump */
    uint8_t tchhyst;          /* 31: Touch threshold hysteresis */
    uint8_t xpitch;           /* 32: X line pitch */
    uint8_t ypitch;           /* 33: Y line pitch */
    uint8_t nexttchdi;        /* 34: Touch detect integration for subsequent touches */
    uint8_t cfg;              /* 35: Configuration (Bitfield: RPTEACHCYCLE, ENHVECT) */
    uint8_t movfilter2;       /* 36: Movement filter 2 (Bitfield: DISABLE, MEDOFF, SPEEDRESP) */
    uint8_t movsmooth;        /* 37: Movement smoothing */
    uint8_t movpred;          /* 38: Movement prediction */
    uint8_t trackthrsf;       /* 39: Tracking threshold scaling factor */
    uint8_t noisethrsf;       /* 40: Noise threshold scaling factor */
    uint8_t reserved_41_44[4];/* 41-44: Reserved */
    uint8_t mrgthradjstr;     /* 45: MRGTHR adjustment strength */
    uint8_t cutoffthr;        /* 46: Cut-off threshold */
} mxt1188s1_t9_config_t;

// T5: Message Processor structure (largest report payload + 1 byte report_id + 1 byte checksum)
typedef struct __packed {
  uint8_t  report_id;
  uint8_t  report_payload[];
  /* uint8_t  checksum; */
} mxt1188s1_t5_message_t;

// Driver internal state structure
typedef struct {
  uint16_t t7_address;
  uint8_t  t7_size;

  uint16_t t9_address;
  uint8_t  t9_size;
  uint8_t  t9_instances;
  uint8_t  t9_report_id_start;
  uint8_t  t9_report_id_end;

  uint16_t t5_address;
  uint8_t  t5_size;

  uint16_t t44_address;
  uint8_t  t44_size;

  uint16_t t6_address;
  uint8_t  t6_size;
  uint8_t  t6_report_id;

  uint16_t x_max;
  uint16_t y_max;
  uint8_t  nr_touches;
} mxt1188s1_driver_info_t;

static mxt1188s1_driver_info_t mxt1188s1_driver;

static bool mxt1188s1_setup(U2HTS_BUS_TYPES bus_type) {
  U2HTS_UNUSED(bus_type);
  memset(&mxt1188s1_driver, 0, sizeof(mxt1188s1_driver));

  U2HTS_LOG_INFO("mXT1188S - Configuration for I2C (addr=0x%x, speed=%dkHz)", 
    MXT1188S1_I2C_ADDR, mxt1188s1.i2c_config.speed_hz / 1000);

  // Switch INT pin to input with pull-up so CHG (open-drain) can operate
  u2hts_tpint_set_mode(false /* input */, true /* pull-up */);

  // Hardware reset sequence.
  // mXT1188S1 signals boot completion by asserting CHG (INT pin) low.
  u2hts_tprst_set(false);
  u2hts_delay_ms(10);   // RST hold time
  u2hts_tprst_set(true);

  u2hts_delay_ms(300);
  U2HTS_LOG_INFO("mXT1188S - Chip has been reset using RST line.");

  // Read Information block header from address 0x0000
  mxt1188s1_information_block_t info_block;
  if (!mxt1188s1_read(0, &info_block, sizeof(info_block))) {
    U2HTS_LOG_ERROR("%s failed to read information block header", __func__);
    return false;
  }

  uint8_t ver_major = (info_block.version >> 4) & 0x0F;
  uint8_t ver_minor = info_block.version & 0x0F;

  U2HTS_LOG_INFO("mXT1188S - Detected Family=0x%02X, Variant=0x%02X, Firmware Ver=%d.%d, Build=%d, Matrix X=%d, Y=%d, Objects=%d",
                 info_block.family_id, info_block.variant_id, ver_major, ver_minor,
                 info_block.build, info_block.matrix_x_size, info_block.matrix_y_size, info_block.num_objects);

  if (info_block.family_id != MXT1188S1_FAMILY_ID) {
    U2HTS_LOG_WARN("Unexpected Family ID 0x%02X (expected 0x%02X for mXT1188S)", info_block.family_id, MXT1188S1_FAMILY_ID);
  }

  if (info_block.variant_id != MXT1188S1_VARIANT_ID) {
    U2HTS_LOG_WARN("Unexpected Variant ID 0x%02X (expected 0x%02X for mXT1188S)", info_block.variant_id, MXT1188S1_VARIANT_ID);
  }

  // Read object table to locate T7, T44, T9, T5 objects.
  mxt1188s1_object_table_element_t element;
  uint8_t report_id_start = 1;
  for (uint8_t i = 0; i < info_block.num_objects; i++) {
    uint16_t addr = (uint16_t)(sizeof(mxt1188s1_information_block_t) + i * sizeof(mxt1188s1_object_table_element_t));
    if (!mxt1188s1_read(addr, &element, sizeof(element))) {
      U2HTS_LOG_ERROR("%s read error, addr = 0x%04x", __func__, addr);
      return false;
    }

    if (element.type == 7) {
      mxt1188s1_driver.t7_address = element.start_address;
      mxt1188s1_driver.t7_size = element.size + 1;
      U2HTS_LOG_INFO("mXT1188S - Found T7 (Power Config) object at 0x%04x, size = %d",
                     mxt1188s1_driver.t7_address, mxt1188s1_driver.t7_size);
    } else if (element.type == 9) {
      mxt1188s1_driver.t9_report_id_start = report_id_start;
      mxt1188s1_driver.t9_report_id_end = report_id_start + element.num_report_ids - 1;
      mxt1188s1_driver.t9_address = element.start_address;
      mxt1188s1_driver.t9_size = element.size + 1;
      mxt1188s1_driver.t9_instances = element.instances + 1;
      U2HTS_LOG_INFO("mXT1188S - Found T9 object at 0x%04x, size = %d, instances = %d, report_ids = %d..%d",
                     mxt1188s1_driver.t9_address, mxt1188s1_driver.t9_size, mxt1188s1_driver.t9_instances,
                     mxt1188s1_driver.t9_report_id_start, mxt1188s1_driver.t9_report_id_end);
    } else if (element.type == 44) {
      mxt1188s1_driver.t44_address = element.start_address;
      mxt1188s1_driver.t44_size = element.size + 1;
      U2HTS_LOG_INFO("mXT1188S - Found T44 (Message Count) object at 0x%04x, size = %d",
                     mxt1188s1_driver.t44_address, mxt1188s1_driver.t44_size);
    } else if (element.type == 5) {
      mxt1188s1_driver.t5_address = element.start_address;
      mxt1188s1_driver.t5_size = element.size + 1;
      U2HTS_LOG_INFO("mXT1188S - Found T5 (Message Processor) object at 0x%04x, size = %d",
                     mxt1188s1_driver.t5_address, mxt1188s1_driver.t5_size);
    } else if (element.type == 6) {
      mxt1188s1_driver.t6_address = element.start_address;
      mxt1188s1_driver.t6_size = element.size + 1;
      mxt1188s1_driver.t6_report_id = report_id_start;
      U2HTS_LOG_INFO("mXT1188S - Found T6 (Command Processor) object at 0x%04x, size = %d, report_id = %d",
                     mxt1188s1_driver.t6_address, mxt1188s1_driver.t6_size, mxt1188s1_driver.t6_report_id);
    }

    report_id_start += element.num_report_ids * (element.instances + 1);
  }

  // ... T9 object is required because it generates touch reports ...
  if (mxt1188s1_driver.t9_address == 0) {
    U2HTS_LOG_ERROR("%s T9 object not found", __func__);
    return false;
  }

  // ... T44 object is used to get report count in the fifo ...
  if (mxt1188s1_driver.t44_address == 0) {
    U2HTS_LOG_ERROR("%s T44 object not found", __func__);
    return false;
  }

  // ... T5 object is used to retrieve reports from other objects ...
  if (mxt1188s1_driver.t5_address == 0) {
    U2HTS_LOG_ERROR("%s T5 object not found", __func__);
    return false;
  }

  // ... T44 object size should be 1 (report count) ...
  if (mxt1188s1_driver.t44_size != 1) {
    U2HTS_LOG_ERROR("%s T44 object size is not 1", __func__);
    return false;
  }

  // ... T9 object should be at least size of config ...
  if (mxt1188s1_driver.t9_size < sizeof(mxt1188s1_t9_config_t)) {
    U2HTS_LOG_ERROR("%s T9 object size is too small", __func__);
    return false;
  }

  // ... read T9 object ...
  mxt1188s1_t9_config_t t9_config;
  if (!mxt1188s1_read(mxt1188s1_driver.t9_address, &t9_config, sizeof(t9_config))) {
    U2HTS_LOG_ERROR("%s failed to read T9 object", __func__);
    return false;
  }
  mxt1188s1_driver.x_max = t9_config.xrangelsb | ((uint16_t)t9_config.xrangemsb << 8);
  mxt1188s1_driver.y_max = t9_config.yrangelsb | ((uint16_t)t9_config.yrangemsb << 8);
  mxt1188s1_driver.nr_touches = t9_config.numtouch;
  U2HTS_LOG_INFO("mXT1188S - T9 config: Max X: %d, Max Y: %d, Max touches: %d", 
                  mxt1188s1_driver.x_max, mxt1188s1_driver.y_max, mxt1188s1_driver.nr_touches);

  // ... confirm the number of touches that will be reported is within the limits of the driver ...
  if (mxt1188s1_driver.nr_touches > U2HTS_MAX_TPS) {
    U2HTS_LOG_ERROR("mXT1188S - Number of touches %d is greater than U2HTS_MAX_TPS %d", 
                    mxt1188s1_driver.nr_touches, U2HTS_MAX_TPS);
    return false;
  }

  // ... configure touch screen for 100Hz (10ms active scan, 20ms idle scan) ...
  if (mxt1188s1_driver.t7_address != 0) {
    mxt1188s1_t7_power_config_t power_cfg = {
      .idleacqint  = 20,   // 20ms (50Hz) idle scan rate
      .actvacqint  = 10,   // 10ms (100Hz) active touch scan rate
      .actv2idleto = 5,    // 1 second timeout (5 * 200ms) before transitioning to idle
      .cfg         = 0x03  // ACTVPIPEEN (bit 1) | IDLEPIPEEN (bit 0)
    };
    if (!mxt1188s1_write(mxt1188s1_driver.t7_address, &power_cfg, sizeof(power_cfg))) {
      U2HTS_LOG_WARN("mXT1188S - Failed to write T7 power config");
    } else {
      U2HTS_LOG_INFO("mXT1188S - Configured T7 scan rate: 100Hz (10ms active, 20ms idle)");
    }
  }

  // ... on reset mXT1188s sends T6 report with configuration status ...
  while (true) {
    uint8_t buf[mxt1188s1_driver.t5_size];
    if (!mxt1188s1_read(mxt1188s1_driver.t5_address, buf, sizeof(buf))) {
      U2HTS_LOG_ERROR("%s failed to read message", __func__);
      return false;
    }

    uint8_t report_id = buf[0];

    if (report_id == mxt1188s1_driver.t6_report_id) {
      mxt1188s1_report_t6_t *report = (mxt1188s1_report_t6_t *)(buf + 1);
      uint8_t status = report->status;
      if (status & (MXT1188S1_T6_STATUS_COMSERR | MXT1188S1_T6_STATUS_CFGERR | MXT1188S1_T6_STATUS_SIGERR)) {
        U2HTS_LOG_ERROR("mXT1188S - Chip Status After Reset Indicates Error: 0x%02x", status);
        if (status & MXT1188S1_T6_STATUS_COMSERR) {
          U2HTS_LOG_ERROR("      -> Communication error detected");
        }
        if (status & MXT1188S1_T6_STATUS_CFGERR) {
          U2HTS_LOG_ERROR("      -> Configuration error detected");
        }
        if (status & MXT1188S1_T6_STATUS_SIGERR) {
          U2HTS_LOG_ERROR("      -> Signal error detected");
        }
        return false;
      }
      U2HTS_LOG_INFO("mXT1188S - Chip Status After Reset: 0x%02x (%s)", 
                      status, (status == 0x80) ? "RESET" : "OKAY");
    }
    else if (report_id == 0xFF) {
      // ... reached to the end of messages ...
      break;
    }
    else {
      U2HTS_LOG_WARN("Unexpected report id: %d", report_id);
    }    
  }

  U2HTS_LOG_INFO("mXT1188S - Finished configuration.");
  return true;
}

static void mxt1188s1_get_config(u2hts_touch_controller_config* cfg) {
  cfg->max_tps = mxt1188s1_driver.nr_touches;
  cfg->x_max = mxt1188s1_driver.x_max;
  cfg->y_max = mxt1188s1_driver.y_max;
}

static uint8_t isqrt8(uint8_t n);

static bool mxt1188s1_service(void) {
  // ... track report slots assigned to touch id for handling multiple messages per touch point ...
  int8_t tp_slot[U2HTS_MAX_TPS];
  memset(tp_slot, -1, sizeof(tp_slot));
  int8_t next_slot = 0;

  while (true) {

    // ... read message from T5 (message queue) ...
    uint8_t buf[mxt1188s1_driver.t5_size];
    if (!mxt1188s1_read(mxt1188s1_driver.t5_address, buf, sizeof(buf))) {
      U2HTS_LOG_ERROR("%s failed to read message", __func__);
      return false;
    }

    uint8_t report_id = buf[0];

    if (report_id == 0xFF) {
      // ... reached to the end of messages ...
      break;
    }

    // ... if it's a T9 report (touch report), process it ...
    if (report_id >= mxt1188s1_driver.t9_report_id_start && report_id <= mxt1188s1_driver.t9_report_id_end) {
      mxt1188s1_report_t9_t *report = (mxt1188s1_report_t9_t *)(buf + 1);
      
      // ... get the touch id and confirm it is valid ...
      uint8_t touch_id = report_id - mxt1188s1_driver.t9_report_id_start;
      if (touch_id >= mxt1188s1_driver.nr_touches) {
        U2HTS_LOG_WARN("Invalid touch id: %d", touch_id);
        continue;
      }
      
      // ... find slot to report the touch ...
      // ... reuse slot if id is already active (due to multiple T9 reports for the same touch point) ...
      int8_t slot = tp_slot[touch_id];
      if (slot == -1) {
        slot = next_slot++;
        tp_slot[touch_id] = slot;
      }

      // ... parse T9 status ...
      bool fDetect  = (report->status & MXT1188S1_T9_STATUS_DETECT);
      bool fPress   = (report->status & MXT1188S1_T9_STATUS_PRESS);
      bool fRelease = (report->status & MXT1188S1_T9_STATUS_RELEASE);
      bool fMove    = (report->status & MXT1188S1_T9_STATUS_MOVE);
      U2HTS_UNUSED(fPress);
      U2HTS_UNUSED(fRelease);
      U2HTS_UNUSED(fMove);

      // ... get the x and y position (12-bit mode) ...
      uint16_t x = ((uint16_t)report->xposmsb << 4) | ((report->xyposlsb >> 4) & 0x0F);
      uint16_t y = ((uint16_t)report->yposmsb << 4) | (report->xyposlsb & 0x0F);

      // ... handle the case where the touch controller is in 10-bit mode for either x or y ...
      if (mxt1188s1_driver.x_max < 1024) { x = x >> 2; }
      if (mxt1188s1_driver.y_max < 1024) { y = y >> 2; }

      // ... convert touch area to width and height using isqrt ...
      uint16_t width = isqrt8(report->tcharea);
      uint16_t height = isqrt8(report->tcharea);
      
      u2hts_set_tp(slot, fDetect, touch_id, x, y, width, height, report->tchamplitude);      
    }
    else {
      U2HTS_LOG_WARN("Unexpected report id 0x%02X", report_id);
    }

  }

  // ... count the number of active touch points ...
  uint8_t tp_count = 0;
  for (int8_t i = 0; i < U2HTS_MAX_TPS; i++) {
    if (tp_slot[i] != -1) {
      tp_count++;
    }
  }

  if (tp_count == 0) return false;

  u2hts_set_tp_count(tp_count);
  return true;
}

static uint8_t isqrt8(uint8_t n)
{
    uint8_t r = 0;
    if (n >= 64) r |= 8, n -= 64;
    if (n >= (r << 3) + 16) r |= 4, n -= (r << 3) + 16;
    if (n >= (r << 2) +  4) r |= 2, n -= (r << 2) +  4;
    if (n >= (r << 1) +  1) r |= 1;
    return r;
}
